# Softmax Regression
Softmax Regression (synonyms: Multinomial Logistic, Maximum Entropy Classifier, or just Multi-class Logistic Regression) is a generalization of logistic regression that we can use for multi-class classification (under the assumption that the classes are mutually exclusive).

In [1]:
import torch.nn as nn

In [51]:
class Softmax1(nn.Module):
    def __init__(self, in_size, out_size):
        super(Softmax, self).__init__()
        self.linear = nn.Linear(in_size, out_size)
        
    def forward(self, x):
        out = self.linear(x)
        return out

In [52]:
# softmax function in python from scratch

In [36]:
from torch.nn import Linear

In [37]:
import torch

In [53]:
torch.manual_seed(1)

model = Softmax1(2,3)

TypeError: super(type, obj): obj must be an instance or subtype of type

In [44]:
x = torch.tensor([[1.0, 2.0]])

In [45]:
x

tensor([[1., 2.]])

In [47]:
#z = model(x)

In [58]:
z = torch.tensor([[2,5,0], [10, 8, 2], [6,5,1]])
_,yhat = z.max(1)
yhat

tensor([1, 0, 0])

In [61]:
import numpy as np

The numpy.argmax() function returns indices of the max element of the array in a particular axis. 

In [62]:
np.argmax([1,2,4])

2

In [63]:
# Working on 2D array
array = np.arange(12).reshape(3, 4)
print("INPUT ARRAY : \n", array)
 
# No axis mentioned, so works on entire array
print("\nMax element : ", np.argmax(array))
 
# returning Indices of the max element
# as per the indices
print("\nIndices of Max element : ", np.argmax(array, axis=0))
print("\nIndices of Max element : ", np.argmax(array, axis=1))

INPUT ARRAY : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Max element :  11

Indices of Max element :  [2 2 2 2]

Indices of Max element :  [3 3 3]


In [64]:
# multiple choice

z = torch.tensor([[10, 5, 0], [10, 8, 2], [10, 5, 1]])
z

tensor([[10,  5,  0],
        [10,  8,  2],
        [10,  5,  1]])

In [66]:
_, yhat = z.max(1)
yhat

tensor([0, 0, 0])

In [68]:
# exercise 3

class Softmax(nn.Module):
    def __init__(self, in_size, out_size):
        super(Softmax, self).__init__()
        self.linear = nn.Linear(in_size, out_size)
    def forward(self, x):
        out = self.linear(x)
        return out


In [74]:
model = Softmax(2,4)

In [75]:
x = torch.tensor([[1.0, 2.0]])

In [76]:
z = model(x)

In [77]:
_, yhat = z.max(1)

In [78]:
yhat

tensor([1])